### ISSUE TITLE
Error in setScalePivot with balance

### ISSUE THREAD

**Issue by sweet4lorie** [LumaPictures/pymel#115]
_From [shinnerspete](https://code.google.com/u/shinnerspete/) on June 02, 2009 16:29:23_

Maya's setScalePivot call does not take a "balance" argument like
setRotatePivot does.

Calling Transform.setScalePivot is causing an error in the binding to the
Maya API. This pymel method does not accept a balance argument, which is
correct. The argument is errantly being added at line 3249 of nodetypes.py,
which causes this exception.

{{{
Error: _setScalePivotTranslation() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "<maya console>", line 1, in \<module>
  File "MayaPipecheck\mesh.py", line 179, in MoveNonzeroPivot
    node.setScalePivot(zero)
  File
"C:\dev\Python\thirdParty\pymel\pymel_0.9.1\Windows32\Python2.5\pymel\core\nodetypes.py",
line 3251, in setScalePivot
    return self._setScalePivotTranslation(point, space=space, balance=balance)
TypeError: _setScalePivotTranslation() got an unexpected keyword argument
'balance' #
}}}

The solution should be to remove the balance argument being passed to
_setScalePivotTranslation.

Using pymel 0.9.1 under Maya2008

_Original issue: http://code.google.com/p/pymel/issues/detail?id=81_

**Comment by sweet4lorie** [comment]
_From [shinnerspete](https://code.google.com/u/shinnerspete/) on June 02, 2009 16:42:10_

My understanding of the balance arguments may be incorrect. This code example shows
the problem.

cube = pymel.PyNode("pCube1")
zero = (0.0, 0.0, 0.0)
cube.setScalePivot(zero)

**Comment by sweet4lorie** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on June 02, 2009 23:09:03_

hi peter. i haven't had a look at this yet, but before i do can you elaborate a little bit more: are you seeing an 
error or just not getting the expected results?

keep in mind this is an api wrap. compare what you're getting with the api commands of the same/similar name

**Status:** Accepted

**Comment by sweet4lorie** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 18, 2011 14:55:22_

in 2009 and on, MFnTransform.setScalePivot DOES have a balance arg; so this code


import pymel.core as pm
t = pm.nt.Transform('persp')
zero = (0.0, 0.0, 0.0)
t.setScalePivot(zero)

DOES work.  Since we only support last 3 maya versions, closing this ticket.

**Status:** WontFix
