### ISSUE TITLE
Upgrading from pyMel 0.7 to Pymel 0.9.1 results in win32con error during Maya startup

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#122]
_From [earthtoj...@gmail.com](https://code.google.com/u/109044515296603464124/) on July 08, 2009 10:27:29_

What Version of Maya are you using? On what operating system? (Please be as specific as possible and include service packs, 64bit vs 32bit, etc) Maya 2008 Ext 2 32-bit running on Vista 64 bit. What Version of PyMEL are you using? 0.7 upgrading to 0.9.1 What is the expected output? What do you see instead? If possible, provide a few lines of code to reproduce the problem. On Maya startup after upgrading to pymel 0.9.1 the output window prints:

No module named Win32con

If I roll back Pymel to 0.7 the error goes away. Is there a maya.cmds or maya.OpenMaya equivalent to the pymel function in question? ( For example, pymel.listRelatives --> maya.cmds.listRelatives ) If so, does it exhibit the same problem? Please provide any additional information below. We use Pymel heavily in our pipeline and have a lot of python startup scripts.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=87_

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on July 08, 2009 10:46:54_

hmmm... that's very interesting. can you get me a full traceback? if you are
importing pymel in userSetup.py can you comment that out and delay the import of
pymel until maya is completely open. that should give me a full traceback so i know
where to start looking. also, did you do the easyInstall installation method?  i
suspect this is a sub-dependency that did not get downloaded.

**Status:** Accepted  
  **Owner:** chadrik  
  **Labels:** Milestone-0.9.x OpSys-Windows Priority-Critical Type-Defect

**Comment by elrond79** [comment]
_From [earthtoj...@gmail.com](https://code.google.com/u/109044515296603464124/) on July 08, 2009 10:48:49_

In our userSetup.py we import:
\<pre>
\# Maya
import maya.cmds as mayaCmd
import maya.mel as mayaMel
import maya.utils as mayaUtils
from pymel import *

\# Python
import os
\</pre>

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on July 08, 2009 10:51:05_

ok, comment out the pymel import.  then, once maya has fully started, open the script
editor and import pymel.  you should get a full traceback of the error.  paste that
in the comments so i can check it out.

**Comment by elrond79** [comment]
_From [earthtoj...@gmail.com](https://code.google.com/u/109044515296603464124/) on July 08, 2009 10:59:46_

I did a manual install by just replacing the Pymel folder that contained 0.7 with the
0.9.1 Pymel folder from the zip file.

commenting out import of pymel in usersetup.py and doing it from the script editor
after startup prints the following:

from pymel import *
\# Error: No module named win32con
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "R:\Tools\Maya\3rdParty\scripts\pymel\__init__.py", line 1468, in \<module>
\#     import mayahook
\#   File "R:\Tools\Maya\3rdParty\scripts\pymel\mayahook\__init__.py", line 5, in \<module>
\#     from mayautils import *
\#   File "R:\Tools\Maya\3rdParty\scripts\pymel\mayahook\mayautils.py", line 29, in
\<module>
\#     SYSTEM = platform.system()
\#   File "C:\Program Files (x86)\Autodesk\Maya2008\bin\python25.zip\platform.py",
line 1042, in system
\#     return uname()[0]
\#   File "C:\Program Files (x86)\Autodesk\Maya2008\bin\python25.zip\platform.py",
line 960, in uname
\#     release,version,csd,ptype = win32_ver()
\#   File "C:\Program Files (x86)\Autodesk\Maya2008\bin\python25.zip\platform.py",
line 479, in win32_ver
\#     from win32con import HKEY_LOCAL_MACHINE,VER_PLATFORM_WIN32_NT,\
\# ImportError: No module named win32con #

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on July 08, 2009 16:29:59_

hi, can you give me the output of this, run from inside maya:


import os
try: print os.uname()
except: "no uname"
import sys
print sys.platform
try:import win32con
except ImportError: print "no win32con"

**Comment by elrond79** [comment]
_From [earthtoj...@gmail.com](https://code.google.com/u/109044515296603464124/) on July 09, 2009 11:55:26_

import os
try: print os.uname()
except: "no uname"
import sys
print sys.platform
try:import win32con
except ImportError: print "no win32con"
win32
no win32con

**Comment by elrond79** [comment]
_From [earthtoj...@gmail.com](https://code.google.com/u/109044515296603464124/) on July 09, 2009 11:56:14_

That is with pyMel .7 running. Do you need me to try it with 0.9.1 as well?

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on July 13, 2009 18:34:47_

this will be fixed in pymel 0.9.2

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on July 13, 2009 18:36:14_

**Status:** Fixed

**Comment by elrond79** [comment]
_From [earthtoj...@gmail.com](https://code.google.com/u/109044515296603464124/) on July 14, 2009 16:07:47_

Thanks mucho! We will upgrade then.
