### ISSUE TITLE
pymel.ls(sl=True) on curve cvs, raises an error

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#130]
_From [div...@barlier.com](https://code.google.com/u/117398791218376807858/) on August 13, 2009 08:09:35_

What Version of Maya are you using? On what operating system? (Please be as specific as possible and include service packs, 64bit vs 32bit, etc) -2009 SP1 x32 What Version of PyMEL are you using? -0.9.1 What is the expected output? What do you see instead? If possible, provide a few lines of code to reproduce the problem. -simple do a pm.ls(sl=True) on curve cvs Is there a maya.cmds or maya.OpenMaya equivalent to the pymel function in question? ( For example, pymel.listRelatives --> maya.cmds.listRelatives ) If so, does it exhibit the same problem? -nope mc.ls(sl=True), works on curves cv Please provide any additional information below. -error message:
pm.ls(sl=True)
\# Error: count
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "E:/_Python/site-packages\pymel\core\general.py", line 662, in ls
\#     return map(PyNode, util.listForNone(cmds.ls(*args, **kwargs)))
\#   File "E:/_Python/site-packages\pymel\core\nodetypes.py", line 185, in
__init__
\#     stopIndex = startIndex + self.__apimfn__().count()-1
\#   File
"C:\engserv\rbuild\194\build\wrk\optim\runTime\Python\Lib\site-packages\maya\OpenMaya.py",
line 5935, in \<lambda>
\#   File
"C:\engserv\rbuild\194\build\wrk\optim\runTime\Python\Lib\site-packages\maya\OpenMaya.py",
line 34, in _swig_getattr
\# AttributeError: count #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=95_

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on August 31, 2009 18:46:49_

fixed with 0.9.2

**Status:** Fixed
