### ISSUE TITLE
getUVAtPoint arg type error

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#170]
_From [hapgilmo...@gmail.com](https://code.google.com/u/115364546815938125153/) on December 17, 2009 10:25:45_

What Version of Maya are you using? On what operating system? (Please be as specific as possible and include service packs, 64bit vs 32bit, etc) Maya 2009sp1(32bit) on WinXP64 What Version of PyMEL are you using? 0.9.2 What is the expected output? What do you see instead? If possible, provide a few lines of code to reproduce the problem. mesh = PyNode('pSphere1')
closest = mesh.getClosestPoint( [0,0,0] , OpenMaya.MSpace.kWorld )
uv = mesh.getUVAtPoint(closest[0], OpenMaya.MSpace.kWorld,'map1',closest[1])'

Error:
\# Error: in method 'MFnMesh_getUVAtPoint', argument 3 of type 'float2 &'
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "<string>", line 2, in getUVAtPoint
\#   File
"d:\depot\toystory3\main\build\tools\maya\common\python\pymel\core\factories.py",
line 2976, in wrappedApiFunc
\#     result = method( mfn, *do_args )
\#   File
"C:\engserv\rbuild\194\build\wrk\optim\runTime\Python\Lib\site-packages\maya\OpenMaya.py",
line 4411, in getUVAtPoint
\# TypeError: in method 'MFnMesh_getUVAtPoint', argument 3 of type 'float2 &' # Is there a maya.cmds or maya.OpenMaya equivalent to the pymel function in question? ( For example, pymel.listRelatives --> maya.cmds.listRelatives ) If so, does it exhibit the same problem? Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=135_

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on December 18, 2009 09:19:45_

Looks like we're trying to cast to a float * (pointing to an array of size 2),
instead of a float2 &...

**Status:** Accepted  
  **Labels:** Type-Defect Milestone-1.0.x Priority-High

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 03, 2010 23:57:53_

Fixed in 2329a52108386bf45e43df38fe11ca7e015556a6 on master branch

**Status:** Fixed
