### ISSUE TITLE
cannot set matrix attribute

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#192]
_From [wou...@gmail.com](https://code.google.com/u/100885014886775043970/) on January 25, 2010 03:00:28_

i tried to set a matrix attribute with different methods without success

maya 2009, xp 32bits
pymel 1.0.0rc1

here is a bit of outputs. twas all the same with this particular mel error
and the broken string for eval

sk.bindPreMatrix[0].set(dt.Matrix())
// Error: setAttr -type "matrix" "skinCluster1.bindPreMatrix[0]" [1.0, 0.0,
0.0, 0.0] [0.0, 1.0, 0.0, 0.0] [0.0, 0.0, 1.0, 0.0] [0.0, 0.0,€ // 
// Error: Line 1.56: Syntax error // 
\# Error: Error occurred during execution of MEL script
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "E:\Partage\pymel-1.0.0rc1\pymel\core\general.py", line 510, in
setAttr
\#     _mm.eval(cmd)
\# RuntimeError: Error occurred during execution of MEL script # 

i didn't expect to see mel stuff here

_Original issue: http://code.google.com/p/pymel/issues/detail?id=157_

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on January 27, 2010 08:33:20_

well, you can feel better knowing this would not have worked using maya.cmds either.  
this MEL code is being used to circumvent a bug with setting matrix attributes in 
python.  it's not fixed.

-chad

**Status:** Fixed  
  **Labels:** Type-MayaDefectFix
