### ISSUE TITLE
nested sets problem

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#207]
_From [wou...@gmail.com](https://code.google.com/u/100885014886775043970/) on March 13, 2010 02:21:28_

it looks like nested sets cannot be queried as members()
it raises an api error

from pymel.core import *
s1=sets()
s2=sets(s1)
s2.members()

\# Error: Maya Attribute does not exist: u'Unable to determine Pymel type:
the passed MPlug is not valid'
\# Traceback (most recent call last):
\#   File "<maya console>", line 3, in \<module>
\#   File "D:\gfx\pymel\pymel\core\nodetypes.py", line 2745, in members
\#     return list( self.asSelectionSet(flatten) )
\#   File "D:\gfx\pymel\pymel\core\nodetypes.py", line 2363, in __getitem__
\#     return general.PyNode( plug )
\#   File "D:\gfx\pymel\pymel\core\general.py", line 1589, in __new__
\#     pymelType, obj = _getPymelType( argObj, name )
\#   File "D:\gfx\pymel\pymel\core\general.py", line 93, in _getPymelType
\#     raise MayaAttributeError, "Unable to determine Pymel type: the passed
MPlug is not valid"
\# MayaAttributeError: Maya Attribute does not exist: u'Unable to determine
Pymel type: the passed MPlug is not valid' # 

info:
maya 2009sp1 x64
today checkout version from github What is the expected output? What do you see instead? i expected to see a list with pynode of set1 in Does maya.cmds exhibit the same problem? i don't know if maya cmds has a members function but the classic way of
doing it works

cmds.sets('set2', q=1)
\# Result: [u'set1'] #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=172_

**Comment by elrond79** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on March 13, 2010 09:51:53_

fixed

**Status:** Fixed  
  **Owner:** chadrik  
  **Labels:** Type-Defect
