### ISSUE TITLE
conflict with sqlalchemy

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#217]
_From [pierre.a...@gmail.com](https://code.google.com/u/116432443266570551407/) on April 21, 2010 03:06:40_

Describe the problem. If we import sqlalchemy and connect to a databse before importing
pymel.core, there's a crash because of:
\# Error: dictionary changed size during iteration
__ What Version of Maya are you using? 2009
__ On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) 32b & 64b WinXP SP3
But it should occurs on any platform.
__ What Version of PyMEL are you using? 1.0.2
__ What is the expected output? What do you see instead? import pymel.internal.plogging
\# Error: dictionary changed size during iteration
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "S:\python-2_5\lib\pymel\internal\__init__.py", line 4, in \<module>
\#     from plogging import getLogger
\#   File "S:\python-2_5\lib\pymel\internal\plogging.py", line 170, in \<module>
\#     pymelLogFileConfig(getLogConfigFile())
\#   File "S:\python-2_5\lib\pymel\internal\plogging.py", line 116, in
pymelLogFileConfig
\#     for loggerName in root.manager.loggerDict:
\# RuntimeError: dictionary changed size during iteration #

__ If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. from sqlalchemy import create_engine
engine = create_engine(
'mysql://user:pass@host/database?charset=utf8&use_unicode=1',
convert_unicode=True, pool_recycle=3600 )
import pymel.core
( or simply import pymel.internal.plogging )
__ Please provide any additional information below. In pymel.internal.plogging, here are the interesting lines:

for loggerName in root.manager.loggerDict:
    logger = logging.getLogger(loggerName)
    \# make sure you get a COPY of handlers!
    oldLogHandlers[loggerName] = logger.handlers[:] 

It seems that calling logging.getLogger(loggerName), for some of the
sqlalchemy loggers, creates a new logger automatically. So the size of
root.manager.loggerDict changes.

Tested with sqlalchemy 0.5.1 and 0.6.0

_Original issue: http://code.google.com/p/pymel/issues/detail?id=182_

**Comment by elrond79** [comment]
_From [mic.sca...@gmail.com](https://code.google.com/u/101175893772548575279/) on July 23, 2010 03:40:30_

It appears that changing the line

for loggerName in root.manager.loggerDict:

to

for loggerName in list(root.manager.loggerDict):

which means iterating over a copy of the loggerDict, the problem goes away.

**Comment by elrond79** [comment]
_From [*...@thesociable.net](https://code.google.com/u/104082926569171873934/) on December 01, 2010 08:15:40_

Just to be clear, this is not specific to Sqlalchemy. The problem occurs with any logger name containing multiple dots.

For example:
logging.getLogger('mylib.0..10')
import pymel.internal.plogging

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on December 06, 2010 08:47:05_

fixed in latest on github - thanks for the report

**Status:** Fixed
