### ISSUE TITLE
Parenting to the World Errors or TypeErrors

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#219]
_From [jed.hunsaker](https://code.google.com/u/jed.hunsaker/) on May 03, 2010 06:22:50_

Describe the problem. Attempting to unparent a joint (or parent it to the world) results in an 
Error with the parent(someJoint, world=True) method or a TypeError with the 
someJoint.parent(world=True) method. What Version of Maya are you using? 2009 x64 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) Windows 7 Professional (64-bit) and up-to-date What Version of PyMEL are you using? 1.0.2 What is the expected output? What do you see instead? I expect no errors. It should just unparent the joint, which it oddly 
*does* do with the parent(someJoint, world=True) method, but it throws an 
error with that method. If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. someJoint.parent(world=True) Does maya.cmds exhibit the same problem? No. In fact, that's how I'm going to do it until this is fixed. Please provide any additional information below. # Error: super(type, obj): obj must be an instance or subtype of type
\# Traceback (most recent call last):
\#   File "<maya console>", line 4, in \<module>
\#   File "E:\maya\scripts\lavadrop\core\rigging.py", line 64, in 
createStretchyArm
\#     djChain[0].parent(world=True)
\#   File "c:\program files\autodesk\maya2009\python\lib\site-
packages\pymel-1.0.0-py2.5.egg\pymel\core\nodetypes.py", line 1238, in 
__getattr__
\#     res = DependNode.__getattr__(self,attr)
\#   File "c:\program files\autodesk\maya2009\python\lib\site-
packages\pymel-1.0.0-py2.5.egg\pymel\core\nodetypes.py", line 294, in 
__getattr__
\#     return getattr(super(general.PyNode, self), attr)
\# TypeError: super(type, obj): obj must be an instance or subtype of type #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=184_

**Comment by elrond79** [comment]
_From [jed.hunsaker](https://code.google.com/u/jed.hunsaker/) on May 03, 2010 06:37:00_

OK I could swear I had this working before with maya.cmds but now it doesn't seem to be 
working there either. Still though, I think the TypeError is a PyMEL issue.

**Comment by elrond79** [comment]
_From [jed.hunsaker](https://code.google.com/u/jed.hunsaker/) on May 03, 2010 06:46:52_

You know what else? the # Error: No object matches name:  # in the script editor might 
even just be a pymelScrollFieldReporter error because it's not a catchable error. That 
or the parent function is running on its own thread, which I highly doubt.

**Comment by elrond79** [comment]
_From [jed.hunsaker](https://code.google.com/u/jed.hunsaker/) on May 03, 2010 13:29:41_

I get the same error with orientConstraint, pointConstraint and I'm to presume many
more functions would produce the same error. I am replacing these functions with
cmds.orientConstraint, etc. until the problem is fixed.

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 20, 2011 17:43:21_

Tested this is 1.0.2 and latest master, with this code:

import maya.cmds as cmds
import pymel.core as pm

someJoint = pm.createNode('joint')
pm.group()
pm.parent(someJoint, world=True)

pm.group()
someJoint.setParent(world=True)

...and it seemed to work fine.

An error WILL be raised if the object is already parented to the world, but this mirrors the behavior of cmds.parent

I'm going to put this down to a pymelScrollFieldReporter error (which is still highly experimental, and really needs someone to give it some love before it's usable), and close unless I hear that it's still a problem with current pymel, and pymelScrollFieldReport not enabled

**Status:** WontFix
