### ISSUE TITLE
executeDeferred takes exactly 1 argument

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#224]
_From [jed.hunsaker](https://code.google.com/u/jed.hunsaker/) on May 08, 2010 18:50:17_

Describe the problem. pymel.mayautils.executeDeferred() only takes one argument, but the 
maya.utils version allows me to input arguments. What Version of Maya are you using? 2009 x64 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) Windows 7 Professional (64-bit) and up-to-date What Version of PyMEL are you using? 1.0.2 What is the expected output? What do you see instead? i expect to be allowed to do this:

pmu.executeDeferred('someFunc', 'someArg') Does maya.cmds exhibit the same problem? No. In fact, that's how I'm going to do it until this is fixed. Please provide any additional information below. Output Window:

Failed to execute userSetup.py
Traceback (most recent call last):
  File "z:/maya/scripts\userSetup.py", line 6, in \<module>
    ld.setWorkspaceToPortableDrive('/school')
  File "z:/maya/scripts\lavadrop\core\school.py", line 122, in 
setWorkspaceToPortableDrive
    executeDeferred(_setWorkspaceToPortableDrive, path)
TypeError: executeDeferred() takes exactly 1 argument (2 given)

_Original issue: http://code.google.com/p/pymel/issues/detail?id=189_

**Comment by elrond79** [comment]
_From [jed.hunsaker](https://code.google.com/u/jed.hunsaker/) on December 22, 2010 23:39:36_

I'm not sure if this is by design, but it appears that using a lambda gets rid of this.

mu.executeDeferred(lambda *args: Foo(7))

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 20, 2011 17:32:32_

added in 63cd139f51d0cf8dc70958322b6bb46342547126

**Status:** Fixed
