### ISSUE TITLE
TypeError when using Assembly nodes.

### ISSUE THREAD

**Issue by assumptionsoup** [LumaPictures/pymel#23]
Assembly nodes are failing when trying to internally create their MFn object.

Repro (tested with the master branch of pymel on 201459):

```
import pymel.core as pm
pm.loadPlugin('sceneAssembly')
asm = pm.assembly(type='assemblyDefinition')
asm.tx
```

[Fails with a TypeError here](https://github.com/LumaPictures/pymel/blob/2fd4454e6ac8915105247ccf62f1c285e516c34c/pymel/core/general.py#L2218) because the [MFnAssemby constructor](http://help.autodesk.com/cloudhelp/2015/ENU/Maya-SDK/cpp_ref/class_m_fn_assembly.html) can only take an MObject, and it's being passed a MDagObject.

Sadly I can't take this any farther and try to fix the problem myself because my hands are tied legally (for now) =[

**Comment by huguesdk** [comment]
This error happens also with MtoA nodes when accessing attributes. The stack trace is:

```
Error: in method 'new_MFnDependencyNode', argument 1 of type 'MObject &'
Traceback (most recent call last):
  File "<maya console>", line 1, in <module>
  File "/usr/autodesk/maya2017/lib/python2.7/site-packages/pymel/core/nodetypes.py", line 2325, in __getattr__
    return super(GeometryShape, self).__getattr__(attr)
  File "/usr/autodesk/maya2017/lib/python2.7/site-packages/pymel/core/nodetypes.py", line 405, in __getattr__
    return DependNode.attr(self, attr)
  File "/usr/autodesk/maya2017/lib/python2.7/site-packages/pymel/core/nodetypes.py", line 480, in attr
    return self._attr(attr, False)
  File "/usr/autodesk/maya2017/lib/python2.7/site-packages/pymel/core/nodetypes.py", line 526, in _attr
    plug = self.__apimfn__().findPlug(attr, False)
  File "/usr/autodesk/maya2017/lib/python2.7/site-packages/pymel/core/general.py", line 2349, in __apimfn__
    mfn = self.__apicls__(obj)
  File "/local/S/Maya_2017_DI/build/optim/runTime/lib/python2.7/site-packages/maya/OpenMaya.py", line 3651, in __init__
TypeError: in method 'new_MFnDependencyNode', argument 1 of type 'MObject &'
```

This is the code triggering the error (in `core/general.py`):

```python
try:
    mfn = self.__apicls__(obj)
    self.__apiobjects__['MFn'] = mfn

except RuntimeError:
    # when using PyNodes in strange places, like node
    # creation callbacks, the proper MFn does not work yet,
    # so we default to a super class and we don't save it,
    # so that we can get the right one later
    if isinstance(obj, _api.MDagPath):
        mfn = _api.MFnDagNode(obj)
        _logger.warning("Could not create desired MFn. Defaulting to MFnDagNode.")

    elif isinstance(obj, _api.MObject):
        mfn = _api.MFnDependencyNode(obj)
        _logger.warning("Could not create desired MFn. Defaulting to MFnDependencyNode.")
    else:
        raise
return mfn
```

As we can see, the call to `mfn = self.__apicls__(obj)` is inside a try-except block, expecting a `RuntimeError`. Indeed, this call triggers a `RuntimeError` on Windows, and it works, only logging a warning message, but on GNU/Linux, the same code raises a `TypeError` instead, and it’s not caught.

Here is exact error on Windows:

```
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_MFnDependencyNode'.
  Possible C/C++ prototypes are:
    MFnDependencyNode()
    MFnDependencyNode(MObject &,MStatus *)
```

So the easy fix is to simply change the line to:
```python
except (RuntimeError, TypeError):
```

but maybe the error could be fixed more cleanly? Do we know why this call throws an exception? The comment mentions “strange places”, but simply accessing an attribute seems to be a normal use case, doesn’t it?

Tested affected versions: Maya 2015, 2017 and 2018.

**Comment by huguesdk** [comment]
Well, for MtoA nodes, it appears to be an MtoA bug. At plug-in load time, very old code in MtoA forces all of its node types to `kPluginDependNode` for PyMEL. Because of this, when accessing an attribute of an `aiStandIn` for example, PyMEL tries to construct an `MFnDependencyNode` with an `MDagPath` object as first argument, which causes the above error. It should construct an `MFnDagNode` instead, which it correctly does if the old MtoA code is removed. This bug is still present in MtoA 2.0.1.1.
