### ISSUE TITLE
Turning on Mayalive plugin in 2008 & 2009 throws an Exception

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#232]
_From [amor...@gmail.com](https://code.google.com/u/117336922884205642661/) on June 04, 2010 09:58:53_

Describe the problem. Turning on the Mayalive plugin results in a stack trace exception:

\# pymel.core : Updating pymel with pre-loaded plugins: Mayatomr, 
OpenEXRLoader, mayalive # 
\# Error: line 0: 'NoneType' object has no attribute 'hasFn'
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "R:\NAS\Maya\__PyMEL\pymel\core\__init__.py", line 233, in 
\<module>
\#     _installCallbacks()
\#   File "R:\NAS\Maya\__PyMEL\pymel\core\__init__.py", line 231, in 
_installCallbacks
\#     _pluginLoaded( plugin )
\#   File "R:\NAS\Maya\__PyMEL\pymel\core\__init__.py", line 141, in 
_pluginLoaded
\#     addPluginPyNodes()
\#   File "R:\NAS\Maya\__PyMEL\pymel\core\__init__.py", line 114, in 
addPluginPyNodes
\#     inheritance = _factories.getInheritance( mayaType )
\#   File "R:\NAS\Maya\__PyMEL\pymel\internal\factories.py", line 298, in 
getInheritance
\#     if obj.hasFn( api.MFn.kDagNode ):
\# AttributeError: 'NoneType' object has no attribute 'hasFn' # What Version of Maya are you using? 2008 and 2009 both x64 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) x64 Windows XP SP3 What Version of PyMEL are you using? 1.0.2 What is the expected output? What do you see instead? Expect a load of pymel.

import pymel.core as pm results in the above stack trace If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. Does maya.cmds exhibit the same problem? Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=197_

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 18, 2011 16:00:11_

Unfortunately, it seems Maya Live is not available for Fedora, so will have to look into this next time I'm in mac / windows

**Status:** Accepted  
  **Labels:** Type-Defect Priority-High Milestone-1.1.x

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 24, 2011 00:14:30_

fixed in ded665f9c83bb55e76049c2e8f089ae226140ee6

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 24, 2011 00:14:53_

**Status:** Fixed
