### ISSUE TITLE
uiTemplate command error

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#234]
_From [hapgilmo...@gmail.com](https://code.google.com/u/115364546815938125153/) on June 10, 2010 10:14:14_

Describe the problem. uiTemplate("template", exists=True)
\# Error: Too many objects or values.
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "C:\Program Files\Autodesk\Maya2011\Python\lib\site-packages\pymel\core\windows.py", line 406, in uiTemplate
\#     return cmds.uiTemplate(name, exists)
\#   File "C:\Program Files\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\pmcmds.py", line 98, in wrappedCmd
\#     res = new_cmd(*new_args, **new_kwargs)
\# TypeError: Too many objects or values. # What Version of Maya are you using? 2011x64 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) win7 x64 What Version of PyMEL are you using? whatever comes with 2011 now What is the expected output? What do you see instead? expected:
\# Result: False # 

actual:
\# Error: Too many objects or values.
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "C:\Program Files\Autodesk\Maya2011\Python\lib\site-packages\pymel\core\windows.py", line 406, in uiTemplate
\#     return cmds.uiTemplate(name, exists)
\#   File "C:\Program Files\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\pmcmds.py", line 98, in wrappedCmd
\#     res = new_cmd(*new_args, **new_kwargs)
\# TypeError: Too many objects or values. # If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. Does maya.cmds exhibit the same problem? NO Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=199_

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 18, 2011 15:38:06_

fixed in github

**Status:** Fixed
