### ISSUE TITLE
Accessing components on Mesh object fails on empty mesh objects

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#244]
_From [orw...@gmail.com](https://code.google.com/u/111184147392992853679/) on September 16, 2010 03:13:37_

Describe the problem. Accessing components on Mesh object fails on empty mesh objects What Version of Maya are you using? 2009 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) Fedora 8 What Version of PyMEL are you using? 1.0 What is the expected output? What do you see instead? Expected return = None or an empty list,
Errors out If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. Creating an empty shape node:
m = pm.createNode('mesh')

Accessing its components
m.vtx
returns nothing
m.getParent().vtx
returns nothing

but if you try looping throug the returns, or checking the bool state of the result:
if m.vtx: print 'OK'
or
for v in m.vtx: print(v)

it will error out

The issue applies to all (edges, verts and faces) Does maya.cmds exhibit the same problem? n/a Please provide any additional information below. Error:
\# Error: (kInvalidParameter): Object is incompatible with this method
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 1794, in __nonzero__
\#     return self.exists()
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 1899, in exists
\#     if self.__apiobject__() :
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 3290, in __apiobject__
\#     return self.__apimobject__()
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 3283, in __apimobject__
\#     handle = self.__apihandle__()
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 3294, in __apihandle__
\#     handle = self._makeComponentHandle()
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 3487, in _makeComponentHandle
\#     indices = self._standardizeIndices(self._indices)
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 3561, in _standardizeIndices
\#     indices.update(self._flattenIndex(indexObjs))
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 3603, in _flattenIndex
\#     partialIndex=oldPartial))
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 3845, in _sliceToIndices
\#     start, stop, step = slice(start, stop, step).indices(self._dimLength(partialIndex))
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/core/general.py", line 4249, in _dimLength
\#     return self.node().numVertices()
\#   File "<string>", line 2, in numVertices
\#   File "/opt/aardman/lib/python2.5/site-packages/pymel-1.0.0-py2.5.egg/pymel/internal/factories.py", line 1962, in wrappedApiFunc
\#     mfn = apiClass( self.__apiobject__() )
\#   File "/engserv/rbuild/197/build/wrk/optim/runTime/lib/python2.5/site-packages/maya/OpenMaya.py", line 3421, in __init__
\# RuntimeError: (kInvalidParameter): Object is incompatible with this method #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=209_

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on October 05, 2010 18:37:55_

Fixed... the problem is due to the fact that MFnMesh can't be initialized with a mesh that is completely empty.
I wrapped a number of methods to either use mel methods instead, or return default values if there's no mesh... but a number of other methods simply won't work on an empty mesh.  However, it makes sense that most of these won't work, as they would require an actual mesh to work on.
At some point, might want to make a more informative error message though...

**Status:** Fixed
