### ISSUE TITLE
renderLayer.listAdjustments()

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#250]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on November 27, 2010 08:06:48_

From E.Ozgur Yilmaz:

Is there a known issue about querying the renderLayer adjustments with Pymel, both of the codes below gives me errors:

for renderLayer in pm.ls(type='renderLayer'):
renderLayer.listAdjustments()

\# Error: Flag 'layer' must be passed a boolean argument when query flag is set
\# Traceback (most recent call last):
\# File "<maya console>", line 2, in \<module>
\# File "/home/ozgur/maya/scripts/pymel-1.0.2/pymel/core/nodetypes.py", line 1679, in listAdjustments
\# return map( general.PyNode, _util.listForNone( cmds.editRenderLayerAdjustment( layer=self, q=1) ) )
\# File "/home/ozgur/maya/scripts/pymel-1.0.2/pymel/internal/pmcmds.py", line 98, in wrappedCmd
\# res = new_cmd(*new_args, **new_kwargs)
\# TypeError: Flag 'layer' must be passed a boolean argument when query flag is set

for renderLayer in pm.ls(type='renderLayer'):
pm.editRenderLayerAdjustment(layer=renderLayer, q=1)
\# Error: Flag 'layer' must be passed a boolean argument when query flag is set
\# Traceback (most recent call last):
\# File "<maya console>", line 2, in \<module>
\# File "/home/ozgur/maya/scripts/pymel-1.0.2/pymel/internal/pmcmds.py", line 98, in wrappedCmd
\# res = new_cmd(*new_args, **new_kwargs)
\# TypeError: Flag 'layer' must be passed a boolean argument when query flag is set # 

this seems to work though:

for renderLayer in pm.ls(type='renderLayer'):
pm.editRenderLayerAdjustment(renderLayer, q=1)

_Original issue: http://code.google.com/p/pymel/issues/detail?id=216_

**Comment by elrond79** [comment]
_From [felix.ul...@gmx.de](https://code.google.com/u/102870833680846130390/) on November 29, 2010 02:53:32_

I fixed this easily. Its just a matter of arguments. In pymel 1.0.2 this is in line 1679. instead of 

return map( general.PyNode, _util.listForNone( cmds.editRenderLayerAdjustment( layer=self, q=1) ) ) 

it should be:

return map( general.PyNode, _util.listForNone( cmds.editRenderLayerAdjustment( self, layer=1, q=1) ) )

Felix

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 18, 2011 15:05:22_

**Status:** Fixed
