### ISSUE TITLE
ui.RenderWindowEditor().getDisplayImage() fails

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#253]
_From [felix.ul...@gmx.de](https://code.google.com/u/102870833680846130390/) on November 29, 2010 03:34:54_

Describe the problem. Calling ui.RenderWindowEditor('renderView').getDisplayImage() throws a runtime error. What Version of Maya are you using? 2011 SP1 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) CentOS plus 5.5 64 bit, Windows XP SP 3 32bit What Version of PyMEL are you using? 1.0.2 What is the expected output? What do you see instead? The expected output is the number of the currently selected stored image in the renderview window (when a renderview window is open), or -1 if there is no image kept. 
The following output is given:

\# Error: renderWindowEditor: Object 'TearOffPane|renderView' not found.
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "C:\Programme\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\factories.py", line 862, in wrappedMelFunc
\#     return inFunc( self, **kwargs )
\#   File "C:\Programme\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\factories.py", line 588, in newUiFunc
\#     return beforeUiFunc(*args, **kwargs)
\#   File "C:\Programme\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\pmcmds.py", line 98, in wrappedCmd
\#     res = new_cmd(*new_args, **new_kwargs)
\# RuntimeError: renderWindowEditor: Object 'TearOffPane|renderView' not found. # If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. ui.RenderWindowEditor('renderView').getDisplayImage() Does maya.cmds exhibit the same problem? No, maya.cmds.renderWindowEditor('renderView', q=1, displayImage=1) works ok. Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=219_

**Comment by elrond79** [comment]
_From [felix.ul...@gmx.de](https://code.google.com/u/102870833680846130390/) on November 29, 2010 03:37:11_

sorry, the error message contains wrong line numbers, it should be:

\# Error: renderWindowEditor: Object 'TearOffPane|renderView' not found.
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "C:\Programme\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\factories.py", line 915, in wrappedMelFunc
\#     return inFunc( self, **kwargs )
\#   File "C:\Programme\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\factories.py", line 644, in newUiFunc
\#     return beforeUiFunc(*args, **kwargs)
\#   File "C:\Programme\Autodesk\Maya2011\Python\lib\site-packages\pymel\internal\pmcmds.py", line 98, in wrappedCmd
\#     res = new_cmd(*new_args, **new_kwargs)
\# RuntimeError: renderWindowEditor: Object 'TearOffPane|renderView' not found. #

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 17, 2011 00:50:22_

**Status:** Accepted  
  **Owner:** chadrik

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 18, 2011 14:56:51_

**Labels:** Type-Defect
