### ISSUE TITLE
promptForPath' is not defined for pathButtonGrp

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#261]
_From [blazej.f...@googlemail.com](https://code.google.com/u/111955836059932500468/) on January 11, 2011 09:36:32_

When creating a pathButtonGrp and clicking the browse button I get an error.

I imported the core:
import pymel.core as pm

Maya 2009 64 bit
Windows XP 64
pymel 1.0.2

Should show the directory browse window. Instead it outputs:
\# Traceback (most recent call last):
\#   File "N:\tools\pymel-1.0.2\pymel\core\windows.py", line 218, in __call__
\#     return self.func(*self.args, **self.kwargs)
\#   File "N:\tools\pymel-1.0.2\pymel\core\uitypes.py", line 904, in setPathCB
\#     def setPathCB(name):
\# NameError: global name 'promptForPath' is not defined #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=227_

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 18, 2011 11:36:22_

fixed in latest on github

**Status:** Fixed
