### ISSUE TITLE
unloading stereoCamera plugin results in error

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#263]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 20, 2011 10:56:45_

get this error when unloading stereoCamera plugin:

import pymel.core as pm
pm.loadPlugin('

pymel.core : DEBUG : Plugin unloaded: stereoCamera
pymel.core : DEBUG : Removing commands: stereoRigManager
pymel.core : DEBUG : Removing nodes: stereoRigTransform, stereoRigFrustum
Warning: Failed to call script callback
Error: StereoRigTransform
\# Traceback (most recent call last):
\#   File "pymel/core/__init__.py", line 177, in _pluginUnloaded
\#     _factories.removePyNode( nodetypes, node )
\#   File "pymel/internal/factories.py", line 2726, in removePyNode
\#     delattr(dynModule.__class__,pyNodeTypeName)
\# AttributeError: StereoRigTransform

_Original issue: http://code.google.com/p/pymel/issues/detail?id=229_

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 20, 2011 10:57:06_

introduced in 1a1a869b85b85f078848e2f3c70f32f865b65bf8

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 20, 2011 10:57:31_

**Status:** Started  
  **Labels:** Type-Defect Priority-High Milestone-1.1.x

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on January 20, 2011 15:18:03_

fixed in 7203758a9cf3ae162d56a4d786fcdc7d6dcc0d65

**Status:** Fixed
