### ISSUE TITLE
Exception calling getAngleX() on a Joint

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#282]
_From [doruc...@gmail.com](https://code.google.com/u/118178485200877127336/) on June 21, 2011 07:22:43_

Describe the problem. When I call the method getAngleX (or Y, or Z) from a nodetype Joint I get an exception error. All the other methods work fine on this node. What Version of Maya are you using? Maya 2012 64bit

On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc)
Windows XP Professional 64bit (2003 version), service pack 2 What Version of PyMEL are you using? PyMEL v1.0.3 (the one inside Maya) What is the expected output? What do you see instead? The expected output is a float value. Instead, I get this:
\# Error: 'float' object is unsubscriptable
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "C:\Program Files\Autodesk\Maya2012\Python\lib\site-packages\pymel\internal\factories.py", line 1019, in wrappedMelFunc
\#     return returnFunc( inFunc( self, **kwargs ) )
\#   File "C:\Program Files\Autodesk\Maya2012\Python\lib\site-packages\pymel\internal\factories.py", line 2541, in \<lambda>
\#     returnFunc = lambda x: x[0]
\# TypeError: 'float' object is unsubscriptable # If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. joint = 'joint_name'
joint = pm.ls(joint)[0]
pm.select(joint)
angle = joint.getAngleZ() Does maya.cmds exhibit the same problem? no, in maya.cmds the command cmd.joint('joint_name',q=1,ax=1) works fine. Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=248_

**Comment by elrond79** [comment]
_From [guo7...@gmail.com](https://code.google.com/u/116095567994370391572/) on April 12, 2013 08:54:10_

The same problem occured for PyMel v1.0.3, Maya 2013 64bit

**Comment by elrond79** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on April 16, 2013 15:58:26_

fixed in de18f1d9fceae9199c7684c1a36959ad1f76867b on github

**Status:** Fixed
