### ISSUE TITLE
nurbs Curve Shape node .cvs() method generates KeyError MDagPath exception

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#286]
_From [geordiem...@gmail.com](https://code.google.com/u/100001095454321399948/) on August 09, 2011 10:03:16_

Describe the problem:
nurbs Curve Shape node method  .cvs() fails with exception.

What Version of Maya are you using? 2011 x-64 On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) Linux 

What Version of PyMEL are you using? 1.03 What is the expected output? What do you see instead? a list of CV objects If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. theCurve = pm.curve(d=3, p=[(0, 0, 0), (0, 0, 3), (0, 0, 6), (0, 0, 9)])
theCurveShape =  theCurve.getShape()
theCVs = theCurveShape.cvs(0,2)

Does maya.cmds exhibit the same problem? N/A. this is using an api call. Please provide any additional information below. here is the exception it generates:
theCurve.cvs(0,3)
\# Error: 'MDagPath'
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "<string>", line 2, in cvs
\#   File "/sww/tools/bundles/pymel-1.0.3/pymel/internal/factories.py", line 2076, in wrappedApiFunc
\#     result = argHelper.castResult( self, result )
\#   File "/sww/tools/bundles/pymel-1.0.3/pymel/internal/factories.py", line 1641, in castResult
\#     return f( instance, result )
\#   File "/sww/tools/bundles/pymel-1.0.3/pymel/internal/factories.py", line 1238, in \<lambda>
\#     cls.outCast[apiTypeName] = lambda self, x: pymelType(x)
\#   File "/sww/tools/bundles/pymel-1.0.3/pymel/core/general.py", line 4428, in __init__
\#     super(MItComponent, self).__init__(*args, **kwargs)
\#   File "/sww/tools/bundles/pymel-1.0.3/pymel/core/general.py", line 4059, in __init__
\#     super(DiscreteComponent, self).__init__(*args, **kwargs)
\#   File "/sww/tools/bundles/pymel-1.0.3/pymel/core/general.py", line 3676, in __init__
\#     super(DimensionedComponent, self).__init__(*args, **kwargs)
\#   File "/sww/tools/bundles/pymel-1.0.3/pymel/core/general.py", line 3490, in __init__
\#     dag = self.__apiobjects__['MDagPath']
\# KeyError: 'MDagPath' #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=252_

**Comment by elrond79** [comment]
_From [Gabriel....@gmail.com](https://code.google.com/u/103040502010949263532/) on October 03, 2011 08:41:00_

I get the same on Maya 2012, Linux 64bit with the PyMel version that shipped with Maya.
