### ISSUE TITLE
modelEditor Object error

### ISSUE THREAD

**Issue by elrond79** [LumaPictures/pymel#300]
_From [felm...@gmail.com](https://code.google.com/u/103796562824099542424/) on December 28, 2011 16:20:11_

Trying to use the getViewType() of a modelEditor Object is giving me this error:

\# Error: RuntimeError: modelEditor: Object 'viewPanes|modelPanel4' not found. #

I am getting a modelEditor object using :

\> x = getPanel(withFocus=True)

When I try to access that objects getViewType() method I get the error

\> x.getViewType()
\# Error: RuntimeError: modelEditor: Object 'viewPanes|modelPanel4' not found. # What Version of Maya are you using? 2011 x64 2010 09 10 06 04 (Subscription Advantage Pack) On what operating system? (be as specific as possible and include service packs, 64bit vs 32bit, etc) CentOS 5.3 What Version of PyMEL are you using? 1.0.0 What is the expected output? What do you see instead? # Result: u'modelPanel' # If possible, provide a few lines of code to reproduce the problem. It helps us if your code will reproduce the problem from a new scene. Does maya.cmds exhibit the same problem? No

pan = mc.getPanel(withFocus=True)
mc.getPanel(typeOf=pan)
\# Result: u'modelPanel' # Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=266_

**Comment by elrond79** [comment]
_From [felm...@gmail.com](https://code.google.com/u/103796562824099542424/) on December 29, 2011 10:22:09_

Also tried to set the value of one of the show types and received an error:

\> pan = getPanel(withFocus=True)
\> pan.setJoints(val=False)
\# Error: modelEditor: Object 'modelPanel4|modelPanel4' not found.
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "/bc/tools/cent5_64/package/maya/2011.5/lib/python2.6/site-packages/pymel/internal/factories.py", line 889, in wrappedMelFunc
\#     return inFunc( self, **kwargs )
\#   File "/bc/tools/cent5_64/package/maya/2011.5/lib/python2.6/site-packages/pymel/internal/factories.py", line 588, in newUiFunc
\#     return beforeUiFunc(*args, **kwargs)
\#   File "/bc/tools/cent5_64/package/maya/2011.5/lib/python2.6/site-packages/pymel/internal/factories.py", line 588, in newUiFunc
\#     return beforeUiFunc(*args, **kwargs)
\#   File "/bc/tools/cent5_64/package/maya/2011.5/lib/python2.6/site-packages/pymel/internal/factories.py", line 741, in simpleWrapFunc
\#     res = beforeSimpleWrap(*args, **kwargs)
\#   File "/bc/tools/cent5_64/package/maya/2011.5/lib/python2.6/site-packages/pymel/internal/factories.py", line 705, in newFuncWithReturnFunc
\#     res = beforeReturnFunc(*args, **kwargs)
\#   File "/bc/tools/cent5_64/package/maya/2011.5/lib/python2.6/site-packages/pymel/internal/pmcmds.py", line 98, in wrappedCmd
\#     res = new_cmd(*new_args, **new_kwargs)
\# RuntimeError: modelEditor: Object 'modelPanel4|modelPanel4' not found. #
