### ISSUE TITLE
global name 'util'  is not defined in arrays.py error message

### ISSUE THREAD

**Issue by bensledge** [LumaPictures/pymel#369]
When you attempt to append an Array with an axis that doesn't exist you get the following error: 
```
a = Array()
a.append(1, axis=1)

# Error: global name 'util' is not defined
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "pymel/util/arrays.py", line 2053, in append
#     raise ValueError, "cannot append on axis %s, axis does not exist for %s of shape %s" % (axis, util.clsname(self), shape)
# NameError: global name 'util' is not defined # 
```

**Comment by elrond79** [comment]
Thanks for the report - should be fixed now!
