### ISSUE TITLE
[Maya 2014 SP4 x64] AttributeError: 'module' object has no attribute '<RandomThing>'

### ISSUE THREAD

**Issue by KeithSedgeman** [LumaPictures/pymel#383]
Was sent here by: https://github.com/cmcpasserby/pbUDK/issues/2

Setup:
Fresh install of Maya 2014 SP4 x64 (co-existing with 2016 Ext2 SP1 x64)

Problem:
When I run the command `import pymel.core as pm` in Maya 2014, I get the following error.
```
import pymel.core as pm
# pymel.internal.factories : MFnDagNode.model is deprecated # 
# pymel.core : Updating pymel with pre-loaded plugins: DirectConnect, mayaHIK, AbcImport, tiffFloatReader, VectorRender, gpuCache, rotateHelper, Substance, MayaMuscle, AutodeskPacketFile, autoLoader, fbxmaya, matrixNodes, ik2Bsolver, modelingToolkit, OpenEXRLoader, ikSpringSolver, Mayatomr, DDConvexHull-2014_64bit, AbcExport, ArubaTessellator, quatNodes, mayaCharacterization, OneClick, retargeterNodes, sceneAssembly # 
# Error: line 1: 'module' object has no attribute 'HIKComputeReference'
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 297, in <module>
#     _installCallbacks()
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 295, in _installCallbacks
#     _pluginLoaded( plugin )
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 134, in _pluginLoaded
#     _addPluginCommand(pluginName, funcName)
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\core\__init__.py", line 63, in _addPluginCommand
#     _pmcmds.addWrappedCmd(funcName)
#   File "D:\Autodesk\Maya2014\Python\lib\site-packages\pymel\internal\pmcmds.py", line 115, in addWrappedCmd
#     cmd = getattr(maya.cmds, cmdname)
# AttributeError: 'module' object has no attribute 'HIKComputeReference' # 
```
However in 2016, it's fine.

**Comment by KeithSedgeman** [comment]
oh wait, I just moved out/reset the \Docs\maya\ and tried again.  no error this time.

so I must have some global settings breaking it.
