### ISSUE TITLE
Make pymel pip installable

### ISSUE THREAD

**Issue by ryangallen** [LumaPictures/pymel#403]
I'm sure it has been thought about by the maintainers/contributors already but shouldn't pymel be made available on [PyPI](https://pypi.python.org/pypi)? It would be great to be able to `pip install pymel` in a virtualenv and not have to worry about manually setting it up. Has anyone looked into what it would take? It doesn't seem like it's too far off, seeing a setup.py file exists already.

I was able to clone this repo and run `pip install -e /path/to/pymel` however there are some errors that arise right away (`ImportError: No module named ez_setup`, `urllib2.HTTPError: HTTP Error 403: SSL is required`...)

**Comment by 8secz-johndpope** [comment]
same problem - how to install?

(py27) ➜  pymel git:(master) python setup.py
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
Traceback (most recent call last):
  File "setup.py", line 256, in <module>
    main()
  File "setup.py", line 173, in main
    ez_setup.use_setuptools()
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/site-packages/ez_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/site-packages/ez_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/site-packages/ez_setup.py", line 193, in download_setuptools
    src = urlopen(url)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/johndpope/miniconda3/envs/py27/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required

I'm on conda - python2 environment
