### ISSUE TITLE
constraint "getWeight" method doesn't accept target list

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#41]
_From [orenou...@gmail.com](https://code.google.com/u/103437034863527094127/) on January 16, 2008 11:25:17_

Create two objects and an orientConstraint, cannot seem to get the
getWeight method to work :

cons = PyNode('pCube2_orientConstraint1')
type(cons)
\# Result: \<class 'pymel.node.OrientConstraint'> # 
cons.getWeight('pCube1')
\# Error: f() takes exactly 1 argument (2 given)
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\# TypeError: f() takes exactly 1 argument (2 given) # 
cons.getWeight()
\# Error: Target list was empty or contained no valid targets.
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "/usr/local/lib/python2.5/site-packages/pymel/factories.py", line
491, in f
\#     return inFunc( self, **kwargs )
\# RuntimeError: Target list was empty or contained no valid targets.
\#  #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=8_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on January 16, 2008 14:54:18_

**Status:** Fixed

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:25_

**Labels:** Milestone-0.7.x
