### ISSUE TITLE
maya.standalone in sys.modules generates ImportError when pymel tries to init maya

### ISSUE THREAD

**Issue by arubertoson** [LumaPictures/pymel#413]
How to reproduce:
```python
# test_script.py
from maya import standalone
from pymel import core
```
Running the above script with: `mayapy test_script.py` will generate:
```python
pymel.internal.startup : ERROR : maya.standalone was successfully initialized, but pymel failed to import maya.cmds (or it was not populated)
Traceback (most recent call last):
  File "test_script.py", line 2, in <module>
    import pymel.core as pm
  File "/usr/autodesk/maya2018.3/lib/python2.7/site-packages/pymel/core/__init__.py", line 11, in <module>
    _startup.mayaInit()
  File "/usr/autodesk/maya2018.3/lib/python2.7/site-packages/pymel/internal/startup.py", line 123, in mayaInit
    result = _mayaInit(forversion=forversion)
  File "/usr/autodesk/maya2018.3/lib/python2.7/site-packages/pymel/internal/startup.py", line 200, in _mayaInit
    from maya.cmds import about
ImportError: cannot import name about
```

This is due to a check in  _mayaInit function on line 186:
https://github.com/LumaPictures/pymel/blob/c87fa1a517b5b4f006814b89c592157c421daf0e/pymel/internal/startup.py#L186

As we have standalone present in the sys.modules but haven't done any initializing yet pymel (assumes?) that as the standalone module has been imported maya must be initialized. 

It's easily avoidable by staggering imports in functions, is the functionality intended though?

**Comment by chadrik** [comment]
> As we have standalone present in the sys.modules but haven't done any initializing yet pymel (assumes?) that as the standalone module has been imported maya must be initialized.

Great analysis.   I tested rerunning `maya.standalone.initialize(name="python")` multiple times and it seems safe, so it could be possible to remove the check for  `and not sys.modules.has_key('maya.standalone')`.  To be confident that this is safe we would need to dig back in the git history for this file to see if there was an explanation for why the check was added (i.e. was the maya.standalone check added separately from the aboutExists check?).  

Out of curiosity, is there a reason you need to import `maya.standalone`?

**Comment by arubertoson** [comment]
Yeah, so I was fiddling around making a generic pytest fixture module that could be used across multiple projects and by chance I started running in to this issue, since I had the `from maya import standalone` at the top. 

I've since moved the import statement to only be used if maya hasn't already been initialized by either pymel, or some other source so I believe encountering this actually made my code a bit safer :)
