### ISSUE TITLE
No module find-even in list 

### ISSUE THREAD

**Issue by Sunghyogun2** [LumaPictures/pymel#466]
Error when I enter code :

mayapy -m pip install "pymel>=1.2.,<1.3."

to install module

.....

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 29, in _iter_built
    for version, func in infos:
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 272, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\index\package_finder.py", line 851, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\index\package_finder.py", line 798, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\index\package_finder.py", line 758, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\index\collector.py", line 490, in fetch_page
    return _get_html_page(location, session=self.session)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\index\collector.py", line 400, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\index\collector.py", line 115, in _get_html_response
    resp = session.get(
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_internal\network\session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Autodesk\Maya2023\Python\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

***************

 modules

Please wait a moment while I gather a list of all available modules...

PySide2             _tracemalloc        hashlib             sched
__future__          _uuid               heapq               secrets
_abc                _warnings           hmac                select
_aix_support        _weakref            html                selectors
_ast                _weakrefset         http                setuptools
_asyncio            _winapi             idlelib             shelve
_bisect             _xxsubinterpreters  imaplib             shiboken2
_blake2             _zoneinfo           imath               shiboken2_generator
_bootlocale         abc                 imghdr              shiboken_tool
_bootsubprocess     aifc                imp                 shlex
_bz2                alembic             importlib           shutil
_codecs             antigravity         inspect             signal
_codecs_cn          argparse            io                  site
_codecs_hk          array               ipaddress           smtpd
_codecs_iso2022     ast                 itertools           smtplib
_codecs_jp          asynchat            json                sndhdr
_codecs_kr          asyncio             keyword             socket
_codecs_tw          asyncore            lib2to3             socketserver
_collections        atexit              libfuturize         sqlite3
_collections_abc    audioop             libpasteurize       sre_compile
_compat_pickle      base64              linecache           sre_constants
_compression        bdb                 locale              sre_parse
_contextvars        binascii            logging             ssl
_csv                binhex              lzma                stat
_ctypes             bisect              mailbox             statistics
_ctypes_test        builtins            mailcap             string
_datetime           bz2                 marshal             stringprep
_decimal            cProfile            math                struct
_distutils_hack     calendar            maya                subprocess
_elementtree        cgi                 mimetypes           sunau
_functools          cgitb               mmap                symbol
_hashlib            chunk               modulefinder        symtable
_heapq              cmath               moverlay            sys
_imp                cmd                 msilib              sysconfig
_io                 code                msvcrt              tabnanny
_json               codecs              multiprocessing     tarfile
_locale             codeop              netrc               telnetlib
_lsprof             collections         nntplib             tempfile
_lzma               colorsys            nt                  test
_markupbase         compileall          ntpath              textwrap
_md5                concurrent          nturl2path          this
_msi                configparser        numbers             threading
_multibytecodec     contextlib          opcode              time
_multiprocessing    contextvars         operator            timeit
_opcode             copy                optparse            tkinter
_operator           copyreg             os                  token
_osx_support        crypt               parser              tokenize
_overlapped         csv                 past                trace
_peg_parser         ctypes              pathlib             traceback
_pickle             curses              pdb                 tracemalloc
_py_abc             dataclasses         pickle              tty
_pydecimal          datetime            pickletools         turtle
_pyio               dbm                 pip                 turtledemo
_queue              decimal             pipes               types
_random             difflib             pkg_resources       typing
_sha1               dis                 pkgutil             ufe
_sha256             distutils           platform            unicodedata
_sha3               doctest             plistlib            unittest
_sha512             email               poplib              urllib
_signal             encodings           posixpath           uu
_sitebuiltins       ensurepip           pprint              uuid
_socket             enum                precompTemplate     venv
_sqlite3            errno               profile             warnings
_sre                faulthandler        pstats              wave
_ssl                filecmp             pty                 weakref
_stat               fileinput           py_compile          webbrowser
_statistics         fnmatch             pyclbr              winreg
_string             formatter           pydoc               winsound
_strptime           fractions           pydoc_data          wsgiref
_struct             ftplib              pyexpat             xdrlib
_symtable           functools           pyside2-rcc-script  xml
_testbuffer         future              pyside2-uic-script  xmlrpc
_testcapi           gc                  pyside_tool         xxsubtype
_testconsole        genericpath         queue               zipapp
_testimportmultiple getopt              quopri              zipfile
_testinternalcapi   getpass             random              zipimport
_testmultiphase     gettext             re                  zlib
_thread             glob                reprlib             zoneinfo
_threading_local    graphlib            rlcompleter
_tkinter            gzip                runpy

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".

**Comment by chadrik** [comment]
This appears to be an issue with urllib3 related to use of proxy servers: https://github.com/pypa/pip/issues/9972

try running upgrading pip first:  

```
mayapy -m pip install -U pip
```

Then run the pymel installation.  

If that doesn't work, then you may need to try some of the suggestions from the issue above, including "uninstalling any proxy software or remove proxy settings".

**Comment by chadrik** [comment]
also, I would just get the latest version of pymel:

```
mayapy -m pip install -U pymel
```
