### ISSUE TITLE
mel2py failes when pass with a script name that resolves to a fullpath with spaces in it

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#49]
_From [kor...@gmail.com](https://code.google.com/u/104328413977123008810/) on January 23, 2008 23:11:53_

---Failes:---
mp.mel2py("myScript",verbosity=1)
\# Error: (2, 'No such file or directory',
path(u'Documents/maya/scripts/myScript.mel'))
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "C:\My Documents\PythonPackages\pymel\mel2py.py", line 255, in mel2py
\#     data = melfile.bytes()
\#   File "C:\Program
Files\Autodesk\Maya2008\Python\lib\site-packages\pymel\path.py", line 525,
in bytes
\#   File "C:\Program
Files\Autodesk\Maya2008\Python\lib\site-packages\pymel\path.py", line 521,
in open
\# IOError: (2, 'No such file or directory',
path(u'Documents/maya/scripts/myScript.mel')) # 

----Works:---
mp.mel2py("C:/My Documents/maya/scripts/myScript.mel",verbosity=1)
converting mel script C:/My Documents/maya/scripts/myScript.mel

_Original issue: http://code.google.com/p/pymel/issues/detail?id=16_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on January 23, 2008 23:28:40_

this is fixed in 7.5 released on highend today

**Status:** Fixed

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:26_

**Labels:** Milestone-0.7.x
