### ISSUE TITLE
setAttr -type "matrix" mysteriously fails

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#54]
_From [kor...@gmail.com](https://code.google.com/u/104328413977123008810/) on February 11, 2008 22:40:02_

I think it's a maya.cmds bug, but I can implement a fix by running it via 
mel:
def setMatrix(attr, mtx):
    pm.setMelGlobal("float[]","$g_matrix",mtx.toList())
    pm.mel.eval("""setAttr "&#37;s" -type "matrix" $g_matrix[0] $g_matrix[1] 
$g_matrix[2] $g_matrix[3] 
                      $g_matrix[4] $g_matrix[5] $g_matrix[6] $g_matrix[7] 
                      $g_matrix[8] $g_matrix[9] $g_matrix[10] $g_matrix
[11] 
                      $g_matrix[12] $g_matrix[13] $g_matrix[14] $g_matrix
[15];""" &#37; attr)

I'm wondering if it's a good idea to implement this directly into the 
Attribute.set method

_Original issue: http://code.google.com/p/pymel/issues/detail?id=21_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 12, 2008 10:01:55_

yes, we should wrap this into the setAttr command. i realize now that i submitted a
bug report to autodesk about this back in august and they suggested using the xform
command instead.  so, i'll use xform behind the scenes to create some functionality
like this:

setAttr( 'persp.worldMatrix', [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], type='matrix' )

also, if the passed type is a pymel Matrix, the type flag will not need to be set:

mat = getAttr( 'persp.worldMatrix' )
setAttr( 'persp.worldMatrix', mat )

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 14, 2008 00:35:37_

fixed and committed

**Status:** Fixed

**Comment by chadrik** [comment]
_From [kor...@gmail.com](https://code.google.com/u/104328413977123008810/) on February 15, 2008 11:12:02_

Still erroring (after fixing the 'isinstNance' type...):

// Error: setAttr -type "matrix" "skinCluster1.bindPreMatrix[1]"
Vector([0.24670513857413029, -0.0, -0.96909059153472277, -0.0]) Vector([-€ // 
// Error: Line 1.63: Syntax error // 
\# Error: Error occurred during execution of MEL script
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "h:\documents\Synchronizer\Dev\pymel\core.py", line 818, in setAttr
\#     mm.eval(cmd)
\# RuntimeError: Error occurred during execution of MEL script # 


Try this piece of code (for some reason the 'eval' seems to truncate the value string
and place a '€' symbol... any idea?):
def setMatrix(attr, mtx):
    setMelGlobal("float[]","$g_matrix",mtx.toList())
    mel.eval("""setAttr "%s" -type "matrix" $g_matrix[0] $g_matrix[1] $g_matrix[2]
$g_matrix[3] 
                      $g_matrix[4] $g_matrix[5] $g_matrix[6] $g_matrix[7] 
                      $g_matrix[8] $g_matrix[9] $g_matrix[10] $g_matrix[11] 
                      $g_matrix[12] $g_matrix[13] $g_matrix[14] $g_matrix[15];""" % attr)

**Status:** Accepted

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:40:57_

**Labels:** Milestone-Release0.7

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:01_

**Labels:** Milestone-0.7.x

**Comment by chadrik** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on December 11, 2010 16:26:18_

**Status:** Fixed
