### ISSUE TITLE
Update docs for sets(): need set creation example

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#58]
_From [john.d.b...@gmail.com](https://code.google.com/u/105966220007362900071/) on March 20, 2008 15:41:57_

v0.7.8

Just about lost my mind when trying to create a new set with sets().  Have
to pass in 'None' as the non-kw arg normally used designate the operating
set (objectSet arg in function definition).

Can the docs be updated with a creation example?  Or create a list of
createFlags, and pass in objectSet via sets(*args)?

newSet1 = sets( name='new1', empty=True )
\# Error: sets() takes exactly 1 non-keyword argument (0 given)
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\# TypeError: sets() takes exactly 1 non-keyword argument (0 given) # 

newSet2 = sets( '', name='new2', empty=True )
\# Error: Object  is invalid
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "/corp/home/jburk/maya/scripts/pymel/core.py", line 1140, in sets
\#     return cmds.sets( *args, **kwargs )
\# TypeError: Object  is invalid # 

newSet3 = sets( None, name='new3', empty=True )
print type(PyNode(newSet3))
\<class 'pymel.node.ObjectSet'>

_Original issue: http://code.google.com/p/pymel/issues/detail?id=25_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:34:38_

**Status:** Fixed

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:27_

**Labels:** Milestone-0.7.x
