### ISSUE TITLE
unable to set fileRule using workspace.fileRules class variable

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#61]
_From [john.d.b...@gmail.com](https://code.google.com/u/105966220007362900071/) on April 02, 2008 16:19:16_

0.7.8, Maya 2008, Linux (CentOS-4.5)

print ws.fileRules['particles']
particles
ws.fileRules['particles'] = 'foobar'
\# Error: Flag 'fileRule' must be passed a boolean argument when query flag
is set
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File
"/mainframe/share/internal/devMaya/2008/release/python/pymel/core.py", line
157, in __setitem__
\#     return cmds.workspace( item, **{'q' : 1, self.entryType: [item,
value] } )
\# TypeError: Flag 'fileRule' must be passed a boolean argument when query
flag is set #

_Original issue: http://code.google.com/p/pymel/issues/detail?id=28_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on April 03, 2008 10:09:50_

fixed for next release.  if you need to fix it on your end, on the WorkspaceEntryDict
class replace:

    def __setitem__(self, item, value):
        return cmds.workspace( item, **{'q' : 1, self.entryType: [item, value] } )

with 

    def __setitem__(self, item, value):
        return cmds.workspace( **{self.entryType: [item, value] } )

**Status:** Fixed

**Comment by chadrik** [comment]
_From [john.d.b...@gmail.com](https://code.google.com/u/105966220007362900071/) on April 07, 2008 17:11:29_

am I missing something?  Tried this, and got pretty much the same.

Sorry, don't have much time to dig deeper on this, resorting to mel.eval() to get the
job done (I feel so dirty...)

workspace.fileRules['foo'] = 'bar'
\# Error: Flag 'fileRule' must be passed a boolean argument when query flag is set
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "/mainframe/share/internal/devMaya/2008/release/python/pymel/core.py", line
157, in __setitem__
\#     return cmds.workspace( **{self.entryType: [item, value] } )
\# TypeError: Flag 'fileRule' must be passed a boolean argument when query flag is set #

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on April 07, 2008 17:21:53_

did you do a fresh restart of maya?  seems crazy to me that you would get the message
"must be passed a boolean argument when query flag is set" when the line clearly does
not pass a query flag to workspace (unless self.entryType is 'query', which seems
fairly unlikely). 

i tested this fix and it worked, but maybe i forgot to send part of the fix, so i
will double-check this when i get a free moment.

**Comment by chadrik** [comment]
_From [john.d.b...@gmail.com](https://code.google.com/u/105966220007362900071/) on April 07, 2008 17:33:37_

argh.  Restarting maya did it.

stick a fork in me and call me stupid (and maybe tired); I had thought that a new tab
would be sufficient (checking pymel.__file__ showed it was pointing to the patched
version).  core.pyc not being re-written should have been my first clue.

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:27_

**Labels:** Milestone-0.7.x
