### ISSUE TITLE
KeyError: ('language',)

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#84]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 18, 2008 13:48:15_

What steps will reproduce the problem? 1. import pymel 2. 3. What is the expected output? What do you see instead? Initialized Pymel PyNodes types list in 1.58 sec
\# Error: ('language',)
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\#   File "C:\svn\python\pymel\__init__.py", line 846, in \<module>
\#     import core.pmtypes.factories as factories
\#   File "C:\svn\python\pymel\core\__init__.py", line 11, in \<module>
\#     from language import *
\#   File "C:\svn\python\pymel\core\language.py", line 359, in \<module>
\#     _factories.createFunctions( __name__ )
\#   File "C:\svn\python\pymel\core\pmtypes\factories.py", line 1576, in
createFunctions
\#     for funcName in moduleCmds[ moduleShortName ] :
\# KeyError: ('language',) # What version of the product are you using? On what operating system? pymel r807 Maya 200806
Windows XP Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=51_

**Comment by chadrik** [comment]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 19, 2008 09:31:20_

Problem was an old cache of mayaCmdsList2008.bin

deleted the file and re-generated.

**Status:** Invalid

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:29_

**Labels:** Milestone-0.7.x
