### ISSUE TITLE
OptionVarList tuple?

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#85]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 23, 2008 11:27:57_

OptionVarList class now subclasses tuple instead of list and has a problem.
While changing this back to list corrects the problem, I don't know if
there was an intended value to using tuple.

\>>> optionVar['test01'] = [1,2,3]
\>>> optionVar['test01']
Traceback (most recent call last):
  File "...\<string>", line 1, in \<module>
  File "C:\svn\python\pymel\mayahook\optionvars.py", line 51, in __getitem__
    val = OptionVarList( key, val )
TypeError: tuple() takes at most 1 argument (2 given)

_Original issue: http://code.google.com/p/pymel/issues/detail?id=52_

**Comment by chadrik** [comment]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 23, 2008 11:31:17_

**Cc:** kinetifex

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:40:57_

**Labels:** Milestone-Release0.7

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:02_

**Labels:** Milestone-0.7.x

**Comment by chadrik** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on December 12, 2010 21:58:43_

already fixed in current rev

**Status:** Fixed
