### ISSUE TITLE
pmcmds: 'module' object has no attribute 'getMelRepresentation'

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#86]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 23, 2008 13:45:59_

What steps will reproduce the problem? >>> import maya.cmds as cmds
\>>> cmds.evalDeferred('print "test"')
test

\>>> import pymel
\>>> pymel.evalDeferred('print "test"')
Traceback (most recent call last):
  File "...\<string>", line 1, in \<module>
  File "C:\svn\python\pymel\core\pmtypes\pmcmds.py", line 42, in wrappedCmd
    return cmd(*(util.getMelRepresentation(args)),
AttributeError: 'module' object has no attribute 'getMelRepresentation' What version of the product are you using? On what operating system? r815 / v2008 ext 2 / Windows XP Please provide any additional information below. Discovered when using evalDeferred but I assume it affects other wrapped
commands.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=53_

**Comment by chadrik** [comment]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 23, 2008 14:39:49_

**Labels:** -Priority-Medium Priority-High

**Comment by chadrik** [comment]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 24, 2008 07:43:39_

r816 change corrected issue.

**Status:** Verified

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:40:57_

**Labels:** Milestone-Release0.7

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:02_

**Labels:** Milestone-0.7.x

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:43:57_

**Status:** Fixed
