### ISSUE TITLE
set/get methods for UI gone?

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#87]
_From [kinetifex](https://code.google.com/u/kinetifex/) on September 24, 2008 09:00:17_

What steps will reproduce the problem? gMainWindow = getMelGlobal( 'string', 'gMainWindow')
menu_name = 'Test Menu'
if menu( menu_name, exists=True ):
    deleteUI( menu_name )
setParent( gMainWindow )
m = menu( menu_name )
mi = menuItem('Test Item')

mi.setEnable(False)

m.getLabel() What is the expected output? What do you see instead? Expected Output:

mi.setEnable(False)
\# Result: MayaWindow|Test_Menu|Test_Item # 

m.getLabel()
\# Result: Test Menu # 

Current Output:

mi.setEnable(False)
\# Error: 'MenuItem' object has no attribute 'setEnable'
\# Traceback (most recent call last):
\#   File "<maya console>", line 8, in \<module>
\# AttributeError: 'MenuItem' object has no attribute 'setEnable' # 

m.getLabel()
\# Error: 'Menu' object has no attribute 'getLabel'
\# Traceback (most recent call last):
\#   File "<maya console>", line 1, in \<module>
\# AttributeError: 'Menu' object has no attribute 'getLabel' # What version of the product are you using? On what operating system? r816 / v2008 ext 2 / Windows XP Please provide any additional information below. Looks like previous pythonic behavior for UI has been lost since 0.7.8

_Original issue: http://code.google.com/p/pymel/issues/detail?id=54_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on September 26, 2008 21:01:27_

fixed

**Status:** Fixed

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:29_

**Labels:** Milestone-0.7.x
