### ISSUE TITLE
problems finding reorder

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#88]
_From [kinetifex](https://code.google.com/u/kinetifex/) on October 14, 2008 15:34:46_

What steps will reproduce the problem? 1. import pymel What is the expected output? What do you see instead? Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "C:\svn\python\pymel\__init__.py", line 860, in \<module>
    import core.pmtypes.factories as factories
  File "C:\svn\python\pymel\core\__init__.py", line 3, in \<module>
    from general import *
  File "C:\svn\python\pymel\core\general.py", line 17, in \<module>
    import pmtypes.factories as _factories
  File "C:\svn\python\pymel\core\pmtypes\factories.py", line 8, in \<module>
    import pymel.api as _api
  File "C:\svn\python\pymel\api\__init__.py", line 10, in \<module>
    from conversions import *
  File "C:\svn\python\pymel\api\conversions.py", line 1254, in \<module>
    apiTypeHierarchy, apiClassInfo =
_buildApiCache(rebuildAllButClassInfo=False)
  File "C:\svn\python\pymel\api\conversions.py", line 1188, in _buildApiCache
    _setOverloadedMethod( 'MFnTransform','getRotation', 1 ) #  MEuler
  File "C:\svn\python\pymel\api\conversions.py", line 1170, in
_setOverloadedMethod
    from pymel.util.arrays import reorder
ImportError: cannot import name reorder What version of the product are you using? On what operating system? r851 / v2008 ext 2 / Windows XP Please provide any additional information below.

_Original issue: http://code.google.com/p/pymel/issues/detail?id=55_

**Comment by chadrik** [comment]
_From [kinetifex](https://code.google.com/u/kinetifex/) on October 16, 2008 15:33:28_

simple changed corrected in r852

**Status:** Fixed

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on February 09, 2009 23:42:29_

**Labels:** Milestone-0.7.x
