### ISSUE TITLE
DependencyNode.listAttr broken for compound multi attributes

### ISSUE THREAD

**Issue by chadrik** [LumaPictures/pymel#97]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on March 25, 2009 05:21:16_

If a node has a compound multi attribute on it, calling node.listAttr()
causes an error:

\>>> mynode = createNode('plusMinusAverage')
\>>> mynode.listAttr()

\# Error: Maya Attribute does not exist: u'plusMinusAverage1.input2D.input2Dx'

_Original issue: http://code.google.com/p/pymel/issues/detail?id=65_

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on March 25, 2009 10:14:14_

i tried to reproduce this in 2008 and 2009 and it worked in both.  

In [1]: mynode = createNode('plusMinusAverage')
In [2]: mynode.listAttr()
Out[2]: 
[Attribute(u'plusMinusAverage1.message'),
 Attribute(u'plusMinusAverage1.caching'),
 Attribute(u'plusMinusAverage1.isHistoricallyInteresting'),
 Attribute(u'plusMinusAverage1.nodeState'),
 Attribute(u'plusMinusAverage1.binMembership'),
 Attribute(u'plusMinusAverage1.operation'),
 Attribute(u'plusMinusAverage1.input1D'),
 Attribute(u'plusMinusAverage1.input2D'),
 Attribute(u'plusMinusAverage1.input2D[-1].input2Dx'),
 Attribute(u'plusMinusAverage1.input2D[-1].input2Dy'),
 Attribute(u'plusMinusAverage1.input3D'),
 Attribute(u'plusMinusAverage1.input3D[-1].input3Dx'),
 Attribute(u'plusMinusAverage1.input3D[-1].input3Dy'),
 Attribute(u'plusMinusAverage1.input3D[-1].input3Dz'),
 Attribute(u'plusMinusAverage1.output1D'),
 Attribute(u'plusMinusAverage1.output2D'),
 Attribute(u'plusMinusAverage1.output2Dx'),
 Attribute(u'plusMinusAverage1.output2Dy'),
 Attribute(u'plusMinusAverage1.output3D'),
 Attribute(u'plusMinusAverage1.output3Dx'),
 Attribute(u'plusMinusAverage1.output3Dy'),
 Attribute(u'plusMinusAverage1.output3Dz')]

**Comment by chadrik** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on March 26, 2009 12:43:22_

Odd... here's my full result in 2009:

mynode = createNode('plusMinusAverage')
mynode.listAttr()
\# Error: Maya Attribute does not exist: u'plusMinusAverage1.input2D.input2Dx'
\# Traceback (most recent call last):
\#   File "<maya console>", line 2, in \<module>
\#   File "C:\Dev\Projects\eclipse\workspace\pymel\core\nodetypes.py", line 2202, in
listAttr
\#     return map( lambda x: self.attr(x), util.listForNone(cmds.listAttr(self.name(),
**kwargs)))
\#   File "C:\Dev\Projects\eclipse\workspace\pymel\core\nodetypes.py", line 2202, in
\<lambda>
\#     return map( lambda x: self.attr(x), util.listForNone(cmds.listAttr(self.name(),
**kwargs)))
\#   File "C:\Dev\Projects\eclipse\workspace\pymel\core\nodetypes.py", line 2141, in attr
\#     raise MayaAttributeError( '%s.%s' % (self, attr) )
\# MayaAttributeError: Maya Attribute does not exist:
u'plusMinusAverage1.input2D.input2Dx' #

**Comment by chadrik** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on March 26, 2009 13:23:17_

Seems the original error was thrown in nodetypes.py, line 2125 - looks like another
stringification error:

import pymel.util.nameparse as nameparse

mynode = createNode('plusMinusAverage')
attr = u'input2D.input2Dx'
nameTokens = nameparse.getBasicPartList( 'dummy.' + attr )
token = nameTokens[1]

mynode.__apimfn__().findPlug(unicode(token))       # Works for me
mynode.__apimfn__().findPlug(token)                # Fails for me

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on March 26, 2009 13:39:15_

but if we're executing the same code, why are you getting a NameParser and i'm not?  do you have 0.7 
compatibility turned on in pymel.conf?

**Comment by chadrik** [comment]
_From [elron...@gmail.com](https://code.google.com/u/112796493857278763022/) on March 26, 2009 13:40:04_

For now, fixed in r1362 , though still want to find out why it worked for Chad...

**Comment by chadrik** [comment]
_From [chad...@gmail.com](https://code.google.com/u/101505156600271307269/) on March 27, 2009 15:53:46_

we suspect this is a windows platform issue, as it does not happen on osx, but have
not had time to further investigate.  the bug is patched.

**Status:** Fixed  
  **Labels:** OpSys-Windows
